/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedGuideRouteImport } from './routes/_authenticated/guide'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedRoadmapItemItemIdRouteImport } from './routes/_authenticated/roadmap.item.$itemId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGuideRoute = AuthenticatedGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapItemItemIdRoute =
  AuthenticatedRoadmapItemItemIdRouteImport.update({
    id: '/item/$itemId',
    path: '/item/$itemId',
    getParentRoute: () => AuthenticatedRoadmapRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/roadmap': typeof AuthenticatedRoadmapRouteWithChildren
  '/roadmap/item/$itemId': typeof AuthenticatedRoadmapItemItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRoute
  '/guide': typeof AuthenticatedGuideRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/roadmap': typeof AuthenticatedRoadmapRouteWithChildren
  '/roadmap/item/$itemId': typeof AuthenticatedRoadmapItemItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/guide': typeof AuthenticatedGuideRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRouteWithChildren
  '/_authenticated/roadmap/item/$itemId': typeof AuthenticatedRoadmapItemItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/guide'
    | '/onboarding'
    | '/roadmap'
    | '/roadmap/item/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/guide'
    | '/onboarding'
    | '/roadmap'
    | '/roadmap/item/$itemId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/guide'
    | '/_authenticated/onboarding'
    | '/_authenticated/roadmap'
    | '/_authenticated/roadmap/item/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/guide': {
      id: '/_authenticated/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthenticatedGuideRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap/item/$itemId': {
      id: '/_authenticated/roadmap/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/roadmap/item/$itemId'
      preLoaderRoute: typeof AuthenticatedRoadmapItemItemIdRouteImport
      parentRoute: typeof AuthenticatedRoadmapRoute
    }
  }
}

interface AuthenticatedRoadmapRouteChildren {
  AuthenticatedRoadmapItemItemIdRoute: typeof AuthenticatedRoadmapItemItemIdRoute
}

const AuthenticatedRoadmapRouteChildren: AuthenticatedRoadmapRouteChildren = {
  AuthenticatedRoadmapItemItemIdRoute: AuthenticatedRoadmapItemItemIdRoute,
}

const AuthenticatedRoadmapRouteWithChildren =
  AuthenticatedRoadmapRoute._addFileChildren(AuthenticatedRoadmapRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedGuideRoute: typeof AuthenticatedGuideRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedGuideRoute: AuthenticatedGuideRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
